export const SCREENS = {
    SPLASH: 'SPLASH',
    HOME: 'HOME_SCREEN',
    LOGIN: 'LOGIN_SCREEN',
    BOOKING_DETAILS: 'BOOKING_DETAILS_SCREEN',
    BOOKING_SUMMARY: 'BOOKING_SUMMARY_SCREEN',
    VEHICLE_LISTING: 'VEHICLE_LISTING_SCREEN',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD_SCREEN',
    COMPLETE_DETAILS: 'COMPLETE_DETAILS_SCREEN',
}