export const SCREENS = {
    SPLASH: 'SPLASH',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD_SCREEN',
    LOGIN: 'LOGIN_SCREEN',
    COMPLETE_DETAILS: 'COMPLETE_DETAILS_SCREEN',
    HOME: 'HOME_SCREEN',
    VEHICLE_LISTING: 'VEHICLE_LISTING_SCREEN'
}