export const STRINGS = {
  APP_NAME: 'Easy Car Relo',
  EMAIL_INPUT_NAME: 'email',
  EMAIL_IS_REQUIRED: 'Email is required.',
  PASSWORD_INPUT_NAME: 'password',
  PASSWORD_IS_REQUIRED: 'Password is required.',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  LOGIN: 'Login',
  SIGNUP: 'Register',
  LOGIN_EMAIL_PLACEHOLDER: 'Email',
  LOGIN_PASSWORD_PLACEHOLDER: 'Password',
  EMAIL_PLACEHOLDER: 'Email',
  PASSWORD_PLACEHOLDER: 'Password',
  FORGOT_PASSWORD: 'Forgot Password?',
  BUTTON_LABEL_LOGIN: 'Log In',
  REMEMBER_ME: 'Remember me',
  EMAIL_IS_INVALID: 'Email is invalid.',
  LOG_IN: 'Log In?',
  FORGOT_LOGIN: 'Log in',
  CHECK_YOUR_MAIL: 'Check your mail!',
  LOGOUT: 'Logout',
  DASHBOARD: 'Dashboard',
  HOME: 'Home',
  NAME_INPUT: 'name',
  SURNAME_INPUT: 'surname',
  DOB_INPUT: 'dob',
  CITY_INPUT: 'city',
  COUNTRY_INPUT: 'country',
  RE_PASSWORD_INPUT_NAME: 're_password',
  NAME_PLACEHOLDER: 'Name',
  SURNAME_PLACEHOLDER: 'Surname',
  DOB_PLACEHOLDER: 'DOB',
  CITY_PLACEHOLDER: 'City',
  COUNTRY_PLACEHOLDER: 'Country',
  RE_PASSWORD_PLACEHOLDER: 'Re-enter password',
  VALUE_CANNOT_BE_ONLY_SPACES: 'Only spaces not allowed.',
  NAME_IS_REQUIRED: 'Name is required.',
  SURNAME_IS_REQUIRED: 'Surname is required.',
  DOB_IS_REQUIRED: 'D.O.B. is required.',
  CITY_IS_REQUIRED: 'City is required.',
  COUNTRY_IS_REQUIRED: 'Country is required.',
  PASSWORD_LENGTH_ERROR: 'Password must be atleast 6 characters long.',
  PASSWORD_DOESNOT_MATCH: 'Passwords mismatch.',
  RE_ENTER_PASSWORD: 'Re-enter your password.',
  COUNTRY_CODE_INPUT: 'country-code',
  PHONE_PLACEHOLDER: 'Phone',
  COUNTRY_CODE_REQUIRED: 'Country code is required.',
  PHONE_NUMBER_REQUIRED: 'Phone is required.',
  PHONE_INVALID: 'Phone number can only have digits.',
  PHONE_NUMBER: 'phone',
  SAVE: 'Save',
  SUBMIT: 'Submit',
  LOGOUT_DESCRIPTION: 'Are you sure you want to logout?',
  CANCEL: 'Cancel',
  CONFIRM: 'Confirm',
  INTERNET_IS_TURNED_OFF: 'Internet connection is turned off',
  LOCATION_PERMISSION_REQUIRED: 'Location permission required',
  DEVICE_GPS_TURNED_OFF: 'Device GPS is turned off',
  YOU_APPEARS_TO_BE_OFFLINE: 'You appears to be offline. Kindly check your internet connection.',
  ALLOW: 'Allow',
  TO_DETECT_CURRENT_LOCATION: 'to automatically detect your current location and show nearby users.',
  TO_TURN_ON_GPS: 'to turn on your phone GPS for accurate location.',
  TO_ENABLE_GO_TO_SETTINGS: 'To enable, go to Settings and turn on location permission.',
  OPEN_SETTINGS: 'Open Settings',
  ALLOW_PERMISSION: 'Allow Permission',
  TURN_ON_GPS: 'Turn on GPS',
  LOGIN_OR_REGISTER: 'Login Or Register',
  I_AM_NEW: "I'm New",
  OR_CONNECT_WITH: 'Or Connect with',
  LOGIN_WITH: 'Log In with',
  GOOGLE: 'Google',
  FACEBOOK: 'Facebook',
  SUBSCRIPTION_TEXT: 'Subscribe for news and promotions.',
  FORGOT_PASSWORD_LABEL: 'Forgot Password',
  RESET_PASSWORD_LINK_SENT: 'Reset password link has been sent to your email address.',
  DID_NOT_RECEIVE_LINK: "Didn't receive the link? ",
  RESEND: 'Resend',
  WE_WILL_SEND_EMAIL: 'We will email you a link to reset your password.',
  YOUR_REQUEST: 'Your Request',
  LOGIN_OR_SIGNUP: 'Login/Signup',
  PROFILE: 'Profile',
  CHANGE_PASSWORD: 'Change Password',
  CURRENT_INPUT_NAME: 'currentPassword',
  NEW_PASSWORD_INPUT_NAME: 'newPassword',
  CURRENT_PASSWORD_PLACEHOLDER: 'Enter current password here...',
  NEW_PASSWORD_PLACEHOLDER: 'Enter new password here...',
  RE_NEW_PASSWORD_PLACEHOLDER: 'Re-enter new password here...',
  CURRENT_PASSWORD_REQUIRED: 'Current password is required.',
  NEW_PASSWORD_REQUIRED: 'New password is required.',
  RATINGS: 'Ratings',
  TRIPS: 'Trips',
  RATING_DETAILS: 'Rating Details',
  TRIP_DETAILS: 'Trip Details',
  CANCEL_RESERVATION: 'Cancel Trip',
  EMAIL_AGENCY: 'Email Agency',
  SUBJECT_PLACEHOLDER: 'Enter Subject',
  TYPE_SUBJECT_HERE: 'Enter subject...',
  TYPE_HERE: 'Type here...',
  SEND_EMAIL: 'Send Email',
  RATE_TRIP: 'Rate Trip',
  EMAIL_BODY_NAME: 'body',
  EMAIL_SUBJECT_NAME: 'subject',
  SUBJECT_REQUIRED: 'Subject is required.',
  BODY_REQUIRED: 'Body is required.',
  HOW_WAS_YOUR_TRIP: 'How was your trip?',
  EDIT_RATING: 'Edit Rating',
  TRIP_DETAILS_SUBHEADING: 'Trip Details:',
  FREE_DAYS_AVAILABLE: 'Free days available:',
  EXTRA_DAYS_AVAILABLE: 'Extra Paid days available:',
  PICKUP_FROM: 'Pick-up from:',
  PICKUP_TIME: 'Pick-up time:',
  DROPOFF_TIME: 'Drop-off time:',
  KILOMETER_ALLOWED: 'Kilometer allowance:',
  ESTIMATED_DISTANCE: 'Estimated travel distance:',
  ADDITIONAL_INFORMATION: 'Additional Information:',
  IMPORTANT_DETAILS: 'Important Details',
  THIS_RELOCATION_INCLUDES: 'This relocation includes:',
  NO_EXTRA_ITEM_FOUND: 'No extra item found for this relocation.',
  BASIC_DETAILS: 'Basic Details: ',
  INSURANCE_NAME: 'Insurance Name: ',
  INSURANCE_DESCRIPTION: 'Insurance Description: ',
  OTHER_INSURANCE_DETAILS: 'Other Insurance Details: ',
  BOND: 'Bond: ',
  EXCESS: 'Excess: ',
  DAILY_FEE: 'Daily Fee: ',
  NO_INSURANCE_FOUND: 'No insurance found for this relocation.',
  PICKUP_BRANCH_DETAILS: 'Pickup Branch Details',
  BRANCH_NAME: 'Branch Name: ',
  CONTACT: 'Contact: ',
  EMAIL_TEXT: 'Email: ',
  ADDRESS: 'Address: ',
  BRANCH_CODE: 'Branch Code: ',
  OPENS_AT: 'Opens At: ',
  CLOSE_BY: 'Closes By: ',
  CITY: 'City',
  DROPOFF_BRANCH_DETAILS: 'Dropoff Branch Details',
  VEHICLE_DETAILS: 'Vehicle Details',
  VEHICLE_NAME: 'Vehicle Name: ',
  VEHICLE_DESCRIPTION: 'Vehicle Description: ',
  FUEL_TYPE: 'Fuel Type:',
  TRANSMISSION_TYPE: 'Transmission Type:',
  VEHICLE_TYPE: 'Vehicle Type:',
  NO_OF_DOORS: 'No. of doors:',
  SMALL_LUGGAGE_CAPACITY: 'Small luggage capacity:',
  LARGE_LUGGAGE_CAPACITY: 'Large luggage capacity:',
  NO_OF_ADULT_SEATS: 'No. of Adult Seats:',
  NO_OF_CHILD_SEATS: 'No. of Child Seats:',
  AIR_CONDITIONING: 'Air conditioning:',
  VEHICLE_CODE: 'Vehicle Code:',
  NO_FAQ_FOUND: 'No FAQs found.',
  SELECT_TRAVEL_DATES: 'Select Travel Dates',
  SELECT_DATES_BEFORE_PROCEEDING: 'Please select your travel dates before proceeding.',
  MAKE_A_REQUEST: 'Make a request',
  OKAY: 'Okay',
};
