export const STRINGS = {
  EMAIL_INPUT_NAME: 'email',
  EMAIL_IS_REQUIRED: 'Email is required.',
  PASSWORD_INPUT_NAME: 'password',
  PASSWORD_IS_REQUIRED: 'Password is required.',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  LOGIN: 'Login',
  SIGNUP: 'SignUp',
  LOGIN_EMAIL_PLACEHOLDER: 'Username or Email',
  LOGIN_PASSWORD_PLACEHOLDER: 'Password',
  EMAIL_PLACEHOLDER: 'Email',
  PASSWORD_PLACEHOLDER: 'Password',
  FORGOT_PASSWORD: 'Forgot Password?',
  BUTTON_LABEL_LOGIN: 'Log In',
  REMEMBER_ME: 'Remember me',
  EMAIL_IS_INVALID: 'Email is invalid.',
  LOG_IN: 'Log In?',
  FORGOT_LOGIN: 'Log in',
  CHECK_YOUR_MAIL: 'Check your mail!',
  LOGOUT: 'Logout',
  DASHBOARD: 'Dashboard',
  HOME: 'Home',
  NAME_INPUT: 'name',
  SURNAME_INPUT: 'surname',
  DOB_INPUT: 'dob',
  CITY_INPUT: 'city',
  COUNTRY_INPUT: 'country',
  RE_PASSWORD_INPUT_NAME: 're_password',
  NAME_PLACEHOLDER: 'Name',
  SURNAME_PLACEHOLDER: 'Surname',
  DOB_PLACEHOLDER: 'DOB',
  CITY_PLACEHOLDER: 'City',
  COUNTRY_PLACEHOLDER: 'Country',
  RE_PASSWORD_PLACEHOLDER: 'Re-enter password',
  VALUE_CANNOT_BE_ONLY_SPACES: 'Only spaces are not allowed as value.',
  NAME_IS_REQUIRED: 'Name is required.',
  SURNAME_IS_REQUIRED: 'Surname is required.',
  DOB_IS_REQUIRED: 'D.O.B. is required.',
  CITY_IS_REQUIRED: 'City is required.',
  COUNTRY_IS_REQUIRED: 'Country is required.',
  PASSWORD_LENGTH_ERROR: 'Password should be 6 to 8 characters long.',
  PASSWORD_DOESNOT_MATCH: 'Your passwords doesnot match.',
  RE_ENTER_PASSWORD: 'Re-enter your password.',
  COUNTRY_CODE_INPUT: 'country-code',
  PHONE_PLACEHOLDER: 'Phone',
  COUNTRY_CODE_REQUIRED: 'Country code is required.',
  PHONE_NUMBER_REQUIRED: 'Phone is required.',
  PHONE_INVALID: 'Invalid phone no.',
  PHONE_NUMBER: 'phone',
  SAVE: 'Save',
  SUBMIT: 'Submit'
}
