export const STRINGS = {
  EMAIL_INPUT_NAME: 'email',
  EMAIL_REQUIRED: 'Email is required.',
  PASSWORD_INPUT_NAME: 'password',
  PASSWORD_REQUIRED: 'Password is required.',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  LOGIN: 'Login',
  PASSWORD_LABEL: 'Password',
  EMAIL_LABEL: 'Email',
  EMAIL_PLACEHOLDER: 'Eg: example@gmail.com',
  PASSWORD_PLACEHOLDER: 'Enter your password',
  FORGOT_PASSWORD: 'Forgot Password?',
  BUTTON_LABEL_LOGIN: 'Log In',
  REMEMBER_ME: 'Remember me',
  EMAIL_INVALID: 'Email is invalid.',
  LOG_IN: 'Log In?',
  FORGOT_LOGIN: 'Log in',
  CHECK_YOUR_MAIL: 'Check your mail!',
  LOGOUT: 'Logout',
  DASHBOARD: 'Dashboard',
  HOME: 'Home',
}
